name: "Check permissions"
description: "Check the user's permissions for the repository"
author: "Your name or organization"

inputs:
  GITHUB_TOKEN:
    description: "The GitHub token to use to authenticate with the GitHub API"
    required: true

outputs:
  is_maintainer:
    description: "Whether the user is a maintainer of the repository"
  is_admin:
    description: "Whether the user is an admin of the repository"
  is_owner:
    description: "Whether the user is the owner of the repository"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.GITHUB_TOKEN }}
  env:
    GITHUB_CONTEXT: ${{ toJson(github) }}


