name: Check user role

on: [push]

jobs:
  check_user_role:
    runs-on: ubuntu-latest
    steps:
    - name: Check user role
      id: check_role
      uses: your_repo/your_action_repo
    - name: Print user role
      run: |
        echo "User is a maintainer: ${{steps.check_role.outputs.is_maintainer}}"
        echo "User is an admin: ${{steps.check_role.outputs.is_admin}}"
        echo "User is the owner: ${{steps.check_role.outputs.is_owner}}"