name: Test action
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test action
      id: test-action
      uses: ./
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{toJson(github.repository)}}

    - name: Print output variables
      run: |
        echo "is_maintainer: ${{ steps.test-action.outputs.is_maintainer }}"
        echo "is_admin: ${{ steps.test-action.outputs.is_admin }}"
        echo "is_owner: ${{ steps.test-action.outputs.is_owner }}"

    # - name: Assert is_maintainer
    #   run: |
    #     if [ "${{ env.is_maintainer }}" = "true" ]; then
    #         echo "is_maintainer is set correctly"
    #     else
    #         echo "is_maintainer is NOT set correctly"
    #         exit 1
    #     fi

    # - name: Assert is_admin
    #   run: |
    #     if [ "${{ env.is_admin }}" = "true" ]; then
    #         echo "is_admin is set correctly"
    #     else
    #         echo "is_admin is NOT set correctly"
    #         exit 1
    #     fi
        
    # - name: Assert is_owner
    #   run: |
    #     if [ "${{ env.is_owner }}" = "true" ]; then
    #         echo "is_owner is set correctly"
    #     else
    #         echo "is_owner is NOT set correctly"
    #         exit 1
    #     fi
