name: Test action
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test action
      id: test-action
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_CONTEXT: ${{ toJson(github) }}

    - name: Print output variables
      run: |
        echo "is_maintainer: ${{ env.is_maintainer }}"
        echo "is_admin: ${{ env.is_admin }}"
        echo "is_owner: ${{ env.is_owner }}"

    - name: Assert is_maintainer
      run: |
        if [ "${{ env.is_maintainer }}" = "true" ]; then
            echo "is_maintainer is set correctly"
        else
            echo "is_maintainer is NOT set correctly"
            exit 1
        fi

    - name: Assert is_admin
      run: |
        if [ "${{ env.is_admin }}" = "true" ]; then
            echo "is_admin is set correctly"
        else
            echo "is_admin is NOT set correctly"
            exit 1
        fi
        
    - name: Assert is_owner
      run: |
        if [ "${{ env.is_owner }}" = "true" ]; then
            echo "is_owner is set correctly"
        else
            echo "is_owner is NOT set correctly"
            exit 1
        fi
