name: CI pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Test action
      id: test_action
      uses: ./  # reference current version of the action in the same repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Print output variables
      run: |
        echo "is_maintainer: ${{ steps.test_action.outputs.is_maintainer }}"
        echo "is_admin: ${{ steps.test_action.outputs.is_admin }}"
        echo "is_owner: ${{ steps.test_action.outputs.is_owner }}"

    - name: Assert output variables
      run: |
        if [ "${{ steps.test_action.outputs.is_maintainer }}" != "true" ]; then exit 1; fi
        if [ "${{ steps.test_action.outputs.is_admin }}" != "true" ]; then exit 1; fi
        if [ "${{ steps.test_action.outputs.is_owner }}" != "true" ]; then exit 1; fi
